// بيانات الأحزاب الستين: رقم الحزب، اسمه، السورة الأولى/الأخيرة، صفحة البداية/النهاية
const QURAN_AHZAB = [
  { number: 1, name: "الحزب الأول", startSurah: 1, startSurahName: "الفاتحة", startAyah: 1, endSurah: 2, endSurahName: "البقرة", endAyah: 75, startPage: 1, endPage: 11 },
  { number: 2, name: "الحزب الثاني", startSurah: 2, startSurahName: "البقرة", startAyah: 76, endSurah: 2, endSurahName: "البقرة", endAyah: 141, startPage: 11, endPage: 21 },
  { number: 3, name: "الحزب الثالث", startSurah: 2, startSurahName: "البقرة", startAyah: 142, endSurah: 2, endSurahName: "البقرة", endAyah: 202, startPage: 21, endPage: 31 },
  { number: 4, name: "الحزب الرابع", startSurah: 2, startSurahName: "البقرة", startAyah: 203, endSurah: 2, endSurahName: "البقرة", endAyah: 252, startPage: 31, endPage: 41 },
  { number: 5, name: "الحزب الخامس", startSurah: 2, startSurahName: "البقرة", startAyah: 253, endSurah: 3, endSurahName: "آل عمران", endAyah: 14, startPage: 42, endPage: 51 },
  { number: 6, name: "الحزب السادس", startSurah: 3, startSurahName: "آل عمران", startAyah: 15, endSurah: 3, endSurahName: "آل عمران", endAyah: 91, startPage: 51, endPage: 61 },
  { number: 7, name: "الحزب السابع", startSurah: 3, startSurahName: "آل عمران", startAyah: 92, endSurah: 3, endSurahName: "آل عمران", endAyah: 170, startPage: 62, endPage: 72 },
  { number: 8, name: "الحزب الثامن", startSurah: 3, startSurahName: "آل عمران", startAyah: 171, endSurah: 4, endSurahName: "النساء", endAyah: 23, startPage: 72, endPage: 81 },
  { number: 9, name: "الحزب التاسع", startSurah: 4, startSurahName: "النساء", startAyah: 24, endSurah: 4, endSurahName: "النساء", endAyah: 86, startPage: 81, endPage: 92 },
  { number: 10, name: "الحزب العاشر", startSurah: 4, startSurahName: "النساء", startAyah: 87, endSurah: 4, endSurahName: "النساء", endAyah: 147, startPage: 92, endPage: 102 },
  { number: 11, name: "الحزب الحادي عشر", startSurah: 4, startSurahName: "النساء", startAyah: 148, endSurah: 5, endSurahName: "المائدة", endAyah: 22, startPage: 102, endPage: 111 },
  { number: 12, name: "الحزب الثاني عشر", startSurah: 5, startSurahName: "المائدة", startAyah: 23, endSurah: 5, endSurahName: "المائدة", endAyah: 81, startPage: 111, endPage: 121 },
  { number: 13, name: "الحزب الثالث عشر", startSurah: 5, startSurahName: "المائدة", startAyah: 82, endSurah: 6, endSurahName: "الأنعام", endAyah: 35, startPage: 121, endPage: 131 },
  { number: 14, name: "الحزب الرابع عشر", startSurah: 6, startSurahName: "الأنعام", startAyah: 36, endSurah: 6, endSurahName: "الأنعام", endAyah: 110, startPage: 132, endPage: 142 },
  { number: 15, name: "الحزب الخامس عشر", startSurah: 6, startSurahName: "الأنعام", startAyah: 111, endSurah: 7, endSurahName: "الأعراف", endAyah: 4, startPage: 142, endPage: 151 },
  { number: 16, name: "الحزب السادس عشر", startSurah: 7, startSurahName: "الأعراف", startAyah: 5, endSurah: 7, endSurahName: "الأعراف", endAyah: 87, startPage: 151, endPage: 161 },
  { number: 17, name: "الحزب السابع عشر", startSurah: 7, startSurahName: "الأعراف", startAyah: 88, endSurah: 7, endSurahName: "الأعراف", endAyah: 170, startPage: 162, endPage: 172 },
  { number: 18, name: "الحزب الثامن عشر", startSurah: 7, startSurahName: "الأعراف", startAyah: 171, endSurah: 8, endSurahName: "الأنفال", endAyah: 40, startPage: 172, endPage: 181 },
  { number: 19, name: "الحزب التاسع عشر", startSurah: 8, startSurahName: "الأنفال", startAyah: 41, endSurah: 9, endSurahName: "التوبة", endAyah: 33, startPage: 181, endPage: 191 },
  { number: 20, name: "الحزب العشرون", startSurah: 9, startSurahName: "التوبة", startAyah: 34, endSurah: 9, endSurahName: "التوبة", endAyah: 92, startPage: 192, endPage: 200 },
  { number: 21, name: "الحزب الحادي والعشرون", startSurah: 9, startSurahName: "التوبة", startAyah: 93, endSurah: 10, endSurahName: "يونس", endAyah: 25, startPage: 201, endPage: 211 },
  { number: 22, name: "الحزب الثاني والعشرون", startSurah: 10, startSurahName: "يونس", startAyah: 26, endSurah: 11, endSurahName: "هود", endAyah: 5, startPage: 211, endPage: 221 },
  { number: 23, name: "الحزب الثالث والعشرون", startSurah: 11, startSurahName: "هود", startAyah: 6, endSurah: 11, endSurahName: "هود", endAyah: 83, startPage: 221, endPage: 231 },
  { number: 24, name: "الحزب الرابع والعشرون", startSurah: 11, startSurahName: "هود", startAyah: 84, endSurah: 12, endSurahName: "يوسف", endAyah: 52, startPage: 231, endPage: 241 },
  { number: 25, name: "الحزب الخامس والعشرون", startSurah: 12, startSurahName: "يوسف", startAyah: 53, endSurah: 13, endSurahName: "الرعد", endAyah: 18, startPage: 241, endPage: 252 },
  { number: 26, name: "الحزب السادس والعشرون", startSurah: 13, startSurahName: "الرعد", startAyah: 19, endSurah: 14, endSurahName: "ابراهيم", endAyah: 52, startPage: 252, endPage: 261 },
  { number: 27, name: "الحزب السابع والعشرون", startSurah: 15, startSurahName: "الحجر", startAyah: 1, endSurah: 16, endSurahName: "النحل", endAyah: 50, startPage: 262, endPage: 272 },
  { number: 28, name: "الحزب الثامن والعشرون", startSurah: 16, startSurahName: "النحل", startAyah: 51, endSurah: 16, endSurahName: "النحل", endAyah: 128, startPage: 272, endPage: 281 },
  { number: 29, name: "الحزب التاسع والعشرون", startSurah: 17, startSurahName: "الإسراء", startAyah: 1, endSurah: 17, endSurahName: "الإسراء", endAyah: 98, startPage: 282, endPage: 292 },
  { number: 30, name: "الحزب الثلاثون", startSurah: 17, startSurahName: "الإسراء", startAyah: 99, endSurah: 18, endSurahName: "الكهف", endAyah: 74, startPage: 292, endPage: 301 },
  { number: 31, name: "الحزب الحادي والثلاثون", startSurah: 18, startSurahName: "الكهف", startAyah: 75, endSurah: 19, endSurahName: "مريم", endAyah: 98, startPage: 301, endPage: 312 },
  { number: 32, name: "الحزب الثاني والثلاثون", startSurah: 20, startSurahName: "طه", startAyah: 1, endSurah: 20, endSurahName: "طه", endAyah: 135, startPage: 312, endPage: 321 },
  { number: 33, name: "الحزب الثالث والثلاثون", startSurah: 21, startSurahName: "الأنبياء", startAyah: 1, endSurah: 21, endSurahName: "الأنبياء", endAyah: 112, startPage: 322, endPage: 331 },
  { number: 34, name: "الحزب الرابع والثلاثون", startSurah: 22, startSurahName: "الحج", startAyah: 1, endSurah: 22, endSurahName: "الحج", endAyah: 78, startPage: 332, endPage: 341 },
  { number: 35, name: "الحزب الخامس والثلاثون", startSurah: 23, startSurahName: "المؤمنون", startAyah: 1, endSurah: 24, endSurahName: "النور", endAyah: 20, startPage: 342, endPage: 351 },
  { number: 36, name: "الحزب السادس والثلاثون", startSurah: 24, startSurahName: "النور", startAyah: 21, endSurah: 25, endSurahName: "الفرقان", endAyah: 20, startPage: 351, endPage: 360 },
  { number: 37, name: "الحزب السابع والثلاثون", startSurah: 25, startSurahName: "الفرقان", startAyah: 21, endSurah: 26, endSurahName: "الشعراء", endAyah: 110, startPage: 361, endPage: 370 },
  { number: 38, name: "الحزب الثامن والثلاثون", startSurah: 26, startSurahName: "الشعراء", startAyah: 111, endSurah: 27, endSurahName: "النمل", endAyah: 55, startPage: 371, endPage: 381 },
  { number: 39, name: "الحزب التاسع والثلاثون", startSurah: 27, startSurahName: "النمل", startAyah: 56, endSurah: 28, endSurahName: "القصص", endAyah: 50, startPage: 381, endPage: 391 },
  { number: 40, name: "الحزب الأربعون", startSurah: 28, startSurahName: "القصص", startAyah: 51, endSurah: 29, endSurahName: "العنكبوت", endAyah: 45, startPage: 391, endPage: 401 },
  { number: 41, name: "الحزب الحادي والأربعون", startSurah: 29, startSurahName: "العنكبوت", startAyah: 46, endSurah: 31, endSurahName: "لقمان", endAyah: 21, startPage: 401, endPage: 412 },
  { number: 42, name: "الحزب الثاني والأربعون", startSurah: 31, startSurahName: "لقمان", startAyah: 22, endSurah: 33, endSurahName: "الأحزاب", endAyah: 30, startPage: 412, endPage: 421 },
  { number: 43, name: "الحزب الثالث والأربعون", startSurah: 33, startSurahName: "الأحزاب", startAyah: 31, endSurah: 34, endSurahName: "سبأ", endAyah: 23, startPage: 421, endPage: 431 },
  { number: 44, name: "الحزب الرابع والأربعون", startSurah: 34, startSurahName: "سبأ", startAyah: 24, endSurah: 36, endSurahName: "يس", endAyah: 27, startPage: 431, endPage: 441 },
  { number: 45, name: "الحزب الخامس والأربعون", startSurah: 36, startSurahName: "يس", startAyah: 28, endSurah: 37, endSurahName: "الصافات", endAyah: 144, startPage: 441, endPage: 450 },
  { number: 46, name: "الحزب السادس والأربعون", startSurah: 37, startSurahName: "الصافات", startAyah: 145, endSurah: 39, endSurahName: "الزمر", endAyah: 31, startPage: 450, endPage: 462 },
  { number: 47, name: "الحزب السابع والأربعون", startSurah: 39, startSurahName: "الزمر", startAyah: 32, endSurah: 40, endSurahName: "غافر", endAyah: 40, startPage: 462, endPage: 471 },
  { number: 48, name: "الحزب الثامن والأربعون", startSurah: 40, startSurahName: "غافر", startAyah: 41, endSurah: 41, endSurahName: "فصلت", endAyah: 46, startPage: 471, endPage: 481 },
  { number: 49, name: "الحزب التاسع والأربعون", startSurah: 41, startSurahName: "فصلت", startAyah: 47, endSurah: 43, endSurahName: "الزخرف", endAyah: 23, startPage: 481, endPage: 490 },
  { number: 50, name: "الحزب الخمسون", startSurah: 43, startSurahName: "الزخرف", startAyah: 24, endSurah: 45, endSurahName: "الجاثية", endAyah: 37, startPage: 490, endPage: 502 },
  { number: 51, name: "الحزب الحادي والخمسون", startSurah: 46, startSurahName: "الأحقاف", startAyah: 1, endSurah: 48, endSurahName: "الفتح", endAyah: 17, startPage: 502, endPage: 513 },
  { number: 52, name: "الحزب الثاني والخمسون", startSurah: 48, startSurahName: "الفتح", startAyah: 18, endSurah: 51, endSurahName: "الذاريات", endAyah: 30, startPage: 513, endPage: 521 },
  { number: 53, name: "الحزب الثالث والخمسون", startSurah: 51, startSurahName: "الذاريات", startAyah: 31, endSurah: 54, endSurahName: "القمر", endAyah: 55, startPage: 521, endPage: 531 },
  { number: 54, name: "الحزب الرابع والخمسون", startSurah: 55, startSurahName: "الرحمن", startAyah: 1, endSurah: 57, endSurahName: "الحديد", endAyah: 29, startPage: 531, endPage: 541 },
  { number: 55, name: "الحزب الخامس والخمسون", startSurah: 58, startSurahName: "المجادلة", startAyah: 1, endSurah: 61, endSurahName: "الصف", endAyah: 14, startPage: 542, endPage: 552 },
  { number: 56, name: "الحزب السادس والخمسون", startSurah: 62, startSurahName: "الجمعة", startAyah: 1, endSurah: 66, endSurahName: "التحريم", endAyah: 12, startPage: 553, endPage: 561 },
  { number: 57, name: "الحزب السابع والخمسون", startSurah: 67, startSurahName: "الملك", startAyah: 1, endSurah: 71, endSurahName: "نوح", endAyah: 28, startPage: 562, endPage: 571 },
  { number: 58, name: "الحزب الثامن والخمسون", startSurah: 72, startSurahName: "الجن", startAyah: 1, endSurah: 77, endSurahName: "المرسلات", endAyah: 50, startPage: 572, endPage: 581 },
  { number: 59, name: "الحزب التاسع والخمسون", startSurah: 78, startSurahName: "النبأ", startAyah: 1, endSurah: 86, endSurahName: "الطارق", endAyah: 17, startPage: 582, endPage: 591 },
  { number: 60, name: "الحزب الستون", startSurah: 87, startSurahName: "الأعلى", startAyah: 1, endSurah: 114, endSurahName: "الناس", endAyah: 6, startPage: 591, endPage: 604 },
];

if (typeof module !== 'undefined' && module.exports) module.exports = { QURAN_AHZAB };